version: '3.9'
services:
  nginx:
    container_name: nginx
    image: nginx
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ssl_certs_conf:/etc/nginx/certs
      - client_static:/var/www/html
      - image_static:/var/www/html/static
    networks: 
      - host
  db:
    image: mongo
    container_name: mongo_store
    restart: always
    # command: 'mongod --auth'
    ports:
      - 27017:27017
    volumes:
      - mongo_storage:/data/db
      - mongo_config:/data/configdb
  # dev_server:
  #   image: node
  #   container_name: api_dev_server
  #   user: 'root'
  #   working_dir: /home/node/app
  #   depends_on:
  #     - db
  #   ports:
  #     - 3000:3000
  #   volumes:
  #     - ./server:/home/node/app
  #   environment:
  #     - DB_URL=db
  #     - NODE_ENV=development
  #     - DB_NAME='transport_dev'
  #     - DB_USER='-'
  #     - DB_PASS='-'
  #     - PORT="3000"
  #   networks:
  #     - back
  #   command: 'npm run dev'
volumes:
  ssl_certs_conf:
    name: ssl_certs_conf
    driver_opts:
      type: nfs
      o: bind
      device: /home/alexey/app/certs

  client_static: 
    name: client_static
    driver_opts:
      type: nfs
      o: bind
      device: /home/alexey/app/inzera-client/dist

  image_static:
    name: image_static
    driver_opts:
      type: nfs
      o: bind
      device: /home/alexey/app/inzera-server/static

  mongo_storage:
    name: mongoStorageVolume
    driver_opts:
      type: nfs
      o: bind
      device: /home/alexey/app/db_data

  mongo_config:
    name: mongoConfigVolume 
    driver_opts:
      type: nfs
      o: bind
      device: /home/alexey/app/db_config

networks:
  host: